/**
 * Section 2 — the inspector, on the tablet. The words a person reads in the
 * walk page; the evidence beside them is the machine's (scripts/inspector-walk.mjs).
 * `do` is the taps in order; `see` what must be on the screen; `why` what the
 * step proves to the room; `ifNot` the fault to suspect. Button names exactly
 * as the screen prints them.
 */
export const ROLE = 'inspector';
export const SECTION = '2';
export const DEVICE = 'phone';
export const TITLE = 'Inspector Walk';
export const EYEBROW = 'the inspector, on the tablet';
export const H1 = { rehearsal: "Inspector walk — every screen, with the machine's own photographs", handout: 'Inspector walk — every screen, step by step' };
export const ACCOUNT = { user: 'inspector1', handout: 'the inspector account you were given' };
export const WALK_CMD = 'node scripts/inspector-walk.mjs';

export const GUIDE = {
  '2.1': { title: 'The inspector\'s home screen', group: 'bench',
    do: ['Sign in as <b>inspector1</b> / password123.', 'Stay on the first screen — do not tap anything yet.'],
    see: ['Two large cards under <em>What are you working on today?</em>: <b>Springs</b> and <b>A wagon</b>.', 'Under them, <b>Your record today</b>: how many springs, how many passed, the band tallies and the newest few with a time each.', 'A green <b>Online</b> dot and <em>Nothing waiting to send</em>.'],
    why: 'The first person to use this screen asked for two things: to see at once whether they are on springs or a wagon, and to see what they have logged. Both are here before a single tap.',
    ifNot: ['No <b>Your record today</b> box: the phone is not reaching the server — check the address and that the certificate was installed (section 1.4).', 'A red <b>Offline</b> dot: Wi‑Fi is off, or the phone has switched to mobile data — turn mobile data off.'] },
  '2.2': { title: 'The sorting bench', group: 'bench',
    do: ['Tap <b>Sorting</b> in the bar (or the <b>Springs</b> card, then <b>Sort springs</b>).'],
    see: ['<b>Bogie type</b> CASNUB 22 NLB, <b>Condition</b> Used (6 bands), <b>Spring position</b> Outer.', 'The strip: six coloured buttons — <span class="band blue">Blue I 263–260</span> <span class="band green">Green II 260–257</span> <span class="band yellow">Yellow III 257–254</span> <span class="band orange">Orange IV 254–251</span> <span class="band white">White V 251–248</span> <span class="band red">Red VI 248–245</span> mm.', 'Below the strip a red <b>Condemn this spring</b> bar and the <b>Gauge</b> picker.'],
    why: 'These are the six bands of the shop\'s own G‑95 Rev‑II (Tables 28–33), not a five-band draft from the internet. The Roman numerals and heights should match the strip on the bench exactly.',
    ifNot: ['Three buttons, not six: <b>Condition</b> is on New — set it to Used.', 'No strip at all, a height box instead: <b>Bogie type</b> is on LWLH25 or LCCF20 (see 2.8).'] },
  '2.3': { title: 'Three springs by the band', group: 'bench',
    do: ['Tap <b>Green</b>, then <b>Yellow</b>, then <b>Blue</b>, a second apart.'],
    see: ['<em>This session:</em> rises 1 → 2 → 3, <em>Passed: 3</em>, and <em>Last:</em> names the band just tapped.', 'A short chime on each tap.', 'In <b>Your record today</b> under the strip: the three new lines at the top, newest first — Blue, then Yellow, then Green — each with the time, ≈height, position, bogie and gauge.'],
    why: 'One tap per spring is the whole bench workflow. At 700 springs a shift nothing else is fast enough, and the record under the strip is how an inspector proves their own count at the end of the day.',
    ifNot: ['The count rises but the record does not change: the record box is fetched from the server after each tap — if the phone is offline it says so and fills in when the network returns (see 2.20).'] },
  '2.4': { title: 'Undo the last tap', group: 'bench',
    do: ['Tap <b>↩ Undo last spring</b> (right, under the strip).'],
    see: ['<em>This session</em> drops by one.', 'A line names what was taken back: <em>Took back BLUE · Band I · 261.5 mm. 2 left in this session.</em>', 'The line disappears from <b>Your record today</b>.'],
    why: 'A wrong tap is a certainty at bench speed, so the undo is one tap and says exactly what it undid. The record keeps a "taken back" mark internally — nothing is silently deleted.',
    ifNot: ['<b>Undo last spring</b> greyed out: the session is empty, or the last tap is still sending — wait a second.'] },
  '2.5': { title: 'Which gauge — and one with no calibration date', group: 'bench',
    do: ['Open the <b>Gauge</b> picker and read the list.', 'Set <b>Spring position</b> to Snubber.', 'Pick <b>SSG‑02</b> in the gauge picker.'],
    see: ['The gauges are named: <b>ISG‑01</b>, <b>OSG‑01</b>, <b>OSG‑02</b>, <b>SSG‑02</b>, each with what it measures.', 'On SSG‑02 an amber note: <em>No calibration date is recorded for this gauge. Readings will be marked accordingly.</em>'],
    why: 'Every reading carries the gauge it was made with, so a drifting gauge can be found later (the admin sees this on the gauge register). An uncalibrated gauge does not stop work — it marks the readings.',
    ifNot: ['No amber note on SSG‑02: the gauge register has a date for it — the admin can check under Gauges; the demo seed leaves it blank on purpose.', 'Set <b>Spring position</b> back to <b>Outer</b> before the next step.'] },
  '2.6': { title: 'Condemn a spring on sight', group: 'bench',
    do: ['Tap the red <b>Condemn this spring</b> bar.', 'Read the panel, tap <b>Back</b> — nothing is recorded.', 'Tap <b>Condemn this spring</b> again, then tap <b>Crack</b>.'],
    see: ['The panel asks <em>What did you see?</em> with <b>Off the strip (height)</b>, <b>Crack</b>, <b>Corrosion</b>, <b>Deformation</b>, <b>Something else</b> and <b>Back</b>.', 'An amber note says that for a crack, corrosion or deformation the photograph is the evidence — switch on photographing (2.7).', 'The tap on <b>Crack</b> records it: <em>Condemned: 1</em>, a low buzz, and in <b>Your record today</b> a red line — <b>Condemned Crack · outer · 22 NLB · OSG‑01</b>.', 'No question about re‑measuring — nothing was measured.'],
    why: 'The reason is the record. A spring condemned for a crack must never be filed as "200 mm" — the record shows the word, not an invented height.',
    ifNot: ['The record line shows a height instead of the reason, or a yellow <em>Worth a second look</em> panel appears asking you to re-measure: the phone is showing an old build — pull down to reload the page once.'] },
  '2.7': { title: 'Photographing while sorting', group: 'bench',
    do: ['Tick <b>Photograph springs while sorting</b>.', 'Put a spring in front of the camera and tap its band.', 'Put your hand in front of the lens and watch the badge.'],
    see: ['The live camera opens directly under the tick box, large (not a thumbnail), with a green <b>Photographing</b> badge.', 'Each band tap saves a frame against the spring — no extra taps.', 'A hand in front → <em>person excluded</em>. It never says "spring 98 %".', '<b>Teach the camera (advanced)</b> stays folded — it is not part of the day\'s work.'],
    why: 'The camera records evidence; it does not decide. The photograph is what a supervisor opens months later to see the crack that condemned the spring.',
    ifNot: ['No camera, a grey box: the browser has no camera permission or the page is on plain http — the address must start with <b>https://</b> and the certificate must be installed (section 1.4).', 'The camera opens somewhere else on the page: reload once.'],
    byHandNote: 'The machine ran this with a fake camera: it proved the camera opens where it should, large, with the badge. The spring and the hand are yours.' },
  '2.8': { title: 'A bogie with no band table', group: 'bench',
    do: ['Untick photographing.', 'Set <b>Bogie type</b> to <b>LWLH25 (BOXNS)</b>.', 'Then set it back to <b>CASNUB 22 NLB</b>.'],
    see: ['The six-button strip disappears; a single <em>Free height — how many mm?</em> box appears.', 'A note: <em>No band table is published for this bogie — serviceable / condemn only. WMM 2.0 §309C</em>.', 'The snubber position splits into Snubber outer / inner (G‑112 Table 26).'],
    why: 'Where the standard publishes no bands, the app refuses to invent them. LWLH25 springs are judged serviceable or condemned against §309C, by a typed height.',
    ifNot: ['A six-button strip on LWLH25: that would be an invented table — report it at once.'] },
  '2.9': { title: 'The bench in Hindi', group: 'bench',
    do: ['Tap <b>हिंदी</b> top right.', 'Look at the strip, then tap <b>EN</b> to come back.'],
    see: ['<b>स्प्रिंग छँटाई</b> as the title; the bands read <b>नीला · हरा · पीला · नारंगी · सफ़ेद · लाल</b> in the same colours, with BAND I–VI and the same millimetres.', 'The gauge names (OSG‑01 …) stay as printed on the gauges.'],
    why: 'Numbers and colours are the shared language of the bench; the words follow whoever is holding the phone.',
    ifNot: ['A line still in English inside a Hindi screen: note which one — it is a missing translation, not a fault in the record.'] },
  '2.10': { title: 'One spring, on a wagon — Single Spring', group: 'single',
    do: ['Tap <b>Single Spring</b> in the bar.', 'Note it first asks which wagon and bogie.', 'Scroll to the height box and type <b>258.5</b>, then <b>244</b>, then <b>263.1</b>, then try to type <b>abc</b>.'],
    see: ['258.5 → <b>Green</b>, Band II, <em>Table 28</em> cited.', '244 → <b>CONDEMNED</b> with the reason (below the condemning limit).', '263.1 → over height, condemned.', '"abc" cannot be typed at all — the box only takes a number; nothing crashes.'],
    why: 'The same tables as the bench, but tied to one wagon and bogie so the spring can be traced. Every verdict quotes its table.',
    ifNot: ['A verdict without a table reference: report it — a verdict must always say where it came from.'] },
  '2.11': { title: 'Choosing a wagon', group: 'wagon',
    do: ['Tap <b>Tasks / Home</b>, then the <b>A wagon</b> card.', 'Tap <b>All wagons</b>.', 'Type <b>WR/BCNHL/40112</b> in <em>Or enter the number</em> and tap <b>Select</b> (or pick it from the list).', 'Tap <b>Continue checklist</b>.'],
    see: ['The picker lists the wagons in the shop with their stage; WR/BCNHL/40112 is at <b>Reassembly</b> (stage 5 of 7 on the stage bar).', 'The wagon opens with its tabs: Checklist · Condition report · Release checks · Passport · Parts · Photos (4) · Timeline · Air‑brake test · Sound.'],
    why: 'One wagon is "active" on the phone until you switch; every photograph, reading and part event lands on it.',
    ifNot: ['"No such wagon": check the slashes — WR/BCNHL/40112, capital letters.', 'The picker shows a different set of wagons: the demo data was not seeded — run DEMO‑DATA.cmd (laptop) or <code>bash scripts/rehearsal.sh start</code> (Mac).'] },
  '2.12': { title: 'The checklist', group: 'wagon',
    do: ['Tap the <b>Checklist</b> tab.', 'Pick a category chip (Springs, Wheels & Axles, Bearings …).'],
    see: ['Each item has <b>Pass · Fail · Condemned · Repaired · Replaced</b>.', 'Condemning an item asks for a note; a <b>Mandatory</b> item cannot be skipped.', 'The eight category chips above: Springs, Wheels &amp; Axles, Bearings, Brake System &amp; Rigging, Couplers &amp; Draft Gear, Bogie Frame &amp; Bolster, Friction Wedges, Body &amp; Underframe.'],
    why: 'The eight CASNUB categories from the WMM, item by item, with the standard each item cites.',
    ifNot: ['Buttons greyed out: the wagon is already released, or you are signed in as a role that cannot inspect.'] },
  '2.13': { title: 'Photographs and the blind pocket count', group: 'wagon',
    do: ['Tap the <b>Photos (4)</b> tab.', 'Read the four <b>Pocket counts</b> lines.', 'Tap <b>Recount</b> on Bogie 2 · Side B and look at the counter, then close it.'],
    see: ['Four frames: Bogie 1 · Side A/B, Bogie 2 · Side A/B.', 'Bogie 1 · Side A: <b>7⁄7⁄2 and 7⁄7⁄2 — agree</b>.', 'Bogie 2 · Side B: <em>Counted by Praveen Singh — a blind recount by someone else is needed</em>, and <b>no figures</b>.', 'The counter never shows the expected number — you count what is in the photograph.'],
    why: 'A second person counts without seeing the first count. Only a supervisor sees "6 of 7 outer — one pocket may be empty". This is how a short bogie is caught before the exit gate, without anyone being led.',
    ifNot: ['The inspector\'s screen shows "6 of 7" or "short": that is a leak of the supervisor\'s view — report it.', 'The counter shows "expected 7": same — report it.'] },
  '2.14': { title: 'Parts in, parts out', group: 'wagon',
    do: ['Tap the <b>Parts</b> tab.', 'Read the balance line and open <b>Show every entry</b>.', 'Look at the form: <b>Came off · Went back on · Replaced with new · Scrapped · Not being refitted</b>, then Category, Position, Part, How many.'],
    see: ['The heading <b>Parts in, parts out</b> and a balance such as <em>40 off · 40 back on · 20 % of 41 expected positions covered</em>.', 'In the list: the springs off at Dismantling, one outer spring <b>Replaced with new — crack at the second coil, new from Stores</b>, the rest back on at Reassembly. No warning box about a position with more back on than came off.', 'Recording a part asks which position; Scrapped and Not being refitted ask for a reason.'],
    why: 'Months after the wagon has gone, this list answers "was anything missing" — with the person and the time against each entry.',
    ifNot: ['A red box saying the wagon has no parts record at all: the demo data on this server predates this build — re-seed (DEMO‑DATA.cmd / rehearsal.sh start).'] },
  '2.15': { title: 'The air-brake test proforma', group: 'wagon',
    do: ['Tap the <b>Air‑brake test</b> tab.', 'Type <b>3.2</b> in row 1 <em>Pressure in BP</em>, watch the box, then clear it.'],
    see: ['<b>Single Wagon Test (air brake)</b> — WMM 2.0 §720‑C — 14 rows: 12 readings with the specified range beside each, 2 yes/no rows (<b>As specified</b> / <b>Not</b>).', '3.2 against 4.9–5.1 turns the box red as you type.', 'The foot says how many rows are still blank; <b>Record test</b> refuses until every row is answered.'],
    why: 'The proforma the WMM requires after POH, with each limit beside the box so the person testing does not have to remember it.',
    ifNot: ['The <b>Not</b> button cut off at the right edge: an old build on the phone — reload once.'] },
  '2.16': { title: 'The wagon\'s timeline', group: 'wagon',
    do: ['Tap the <b>Timeline</b> tab.'],
    see: ['Every stage the wagon has passed, with the date and who moved it: Entry registration → Dismantling → Component inspection → Repair → Reassembly.'],
    why: 'Turnaround and "which stage is slow" on the DRM dashboard are computed from exactly these lines — nothing is estimated.',
    ifNot: [] },
  '2.17': { title: 'A wheel, from the chalk on the disc', group: 'wagon',
    do: ['Home → <b>Switch wagon</b> → <b>All wagons</b> → <b>SER/BOXNHL/30914</b> → Continue checklist.', 'On the Checklist tab scroll to the wheels (Axle 1 · bogie 1 … Axle 4 · bogie 2).', 'Tap <b>Axle 1 · Left</b>. Type <b>917</b>.'],
    see: ['One large box: <em>Tread diameter (mm) — the figure chalked on the disc</em>.', 'Under it, as you type: <b>below issue limit</b> — <em>Tread diameter 917 mm — last shop issue 919 mm, condemn 906 mm (WD‑97037‑S‑01 (WMM Ch.6, WD‑88089/S‑1))</em>.', 'Flange figures are folded under <em>Flange and tread figures, if the tyre defect gauge was used (optional)</em>.', 'Axle 3 already reads 917.5 / 917.8 in amber — this is the pair that blocks the wagon at the gate (section 3).'],
    why: 'The one number every wheel has is the chalked diameter; the rest is optional and stays out of the way. The limit and its drawing are quoted, never remembered.',
    ifNot: ['A row of six empty boxes with no verdict: an old build — reload.', 'Tap <b>Cancel</b> — do not record 917 on axle 1; the demo relies on axle 3 being the blocked pair.'] },
  '2.18': { title: 'Reading a wagon number with the camera', group: 'camera',
    do: ['Home → <b>Switch wagon</b> → <b>All wagons</b> → tap the camera icon <b>Read the number painted on the wagon</b>.', 'Point at any printed wagon number (a sheet of paper with <b>SER/BOXNHL/30914</b> in large letters is enough).'],
    see: ['The camera opens with a frame guide.', 'It proposes the text it read; you <b>confirm</b> or correct it. Nothing is recorded until you confirm.'],
    why: 'Eleven characters with gloves on, standing at the wagon, is exactly what a camera is for — but the person, not the camera, commits the number.',
    ifNot: ['Reads nothing after ten seconds: more light, closer, hold still; typing the number is always there beneath.'],
    byHandNote: 'The machine proved the camera opens and the confirm-or-correct wording is there; it had no painted number to read.' },
  '2.19': { title: 'Ask the Manual', group: 'camera',
    do: ['Tap <b>Manual</b> in the bar.', 'Search <b>brake block condemning limit</b>.', 'Then search <b>wheel diameter variation same axle bogie</b>.'],
    see: ['The first hit is labelled <b>ANSWER — IN THE DOCUMENT\'S OWN WORDS</b>, large, with the page number, and a <em>Source:</em> line naming the manual and page.', 'More hits under <b>ALSO IN</b>.', 'The wheel question names <b>IRCA Part III</b> as its source.'],
    why: 'It quotes; it never paraphrases. 8,200 passages from the shipped manuals, on the phone, with no internet. If a passage does not exist it says so rather than inventing one.',
    ifNot: ['"Manual not indexed": run INDEX‑MANUALS.cmd on the laptop (the Mac does this in rehearsal.sh start).'] },
  '2.20': { title: 'Working with no network', group: 'edge',
    do: ['Turn the phone\'s Wi‑Fi off (mobile data is already off).', 'On <b>Sorting</b>, tap three bands.', 'Turn Wi‑Fi back on and wait up to a minute.'],
    see: ['The three record with the usual chime; a banner: <em>3 springs are held on this tablet and will send themselves when the network is back. Nothing is lost.</em>', 'With Wi‑Fi back the banner clears and <b>Your record today</b> gains exactly three lines — no duplicates.'],
    why: 'The shed has dead spots. Work continues; the record catches up; nothing doubles when the network flickers.',
    ifNot: ['The page will not open with Wi‑Fi off: the app was never installed for offline use — that needs the certificate and one visit over https first (section 1.4).', 'Six lines instead of three: report it with the time — that would be a duplicate on resend, which the server is built to refuse.'] },
  '2.21': { title: 'Screens an inspector does not have', group: 'edge',
    do: ['In the address bar add <b>/dashboard</b> to the app address and open it.', 'Do the same with <b>/audit</b>.'],
    see: ['Only the inspector\'s own screens appear — there is no DRM dashboard or audit page to reach by typing.', 'On the server the DRM\'s analytics and the audit data answer <b>403 refused</b> to an inspector\'s sign-in.'],
    why: 'Roles are enforced on the server by capability, not by hiding buttons.',
    ifNot: ['A dashboard with figures on an inspector\'s phone: report it — that is a permission fault.'] },
  '2.22': { title: 'Sign out', group: 'edge',
    do: ['Tap the red <b>Logout</b> in the bar.', 'Press the phone\'s back button.'],
    see: ['The sign-in page.', 'Back does not reopen a signed-in screen.'],
    why: 'A phone left on the bench must not carry a live session.',
    ifNot: [] }
};

export const GROUPS = [
  ['bench', 'The bench — springs', '2.1 – 2.9', 'Sign in as inspector1. Everything here is one tap per spring.'],
  ['single', 'One spring on a wagon', '2.10', 'The same tables, tied to a wagon and bogie.'],
  ['wagon', 'A wagon — WR/BCNHL/40112 and SER/BOXNHL/30914', '2.11 – 2.17', 'Checklist, photographs, parts, the brake proforma, the timeline, a wheel.'],
  ['camera', 'The camera and the manual', '2.18 – 2.19', 'Reading a painted number; asking the manual in its own words.'],
  ['edge', 'No network, no permission, sign out', '2.20 – 2.22', 'What must keep working and what must be refused.']
];

