/**
 * Proving it is really you, before something consequential
 * Indian Railways WRS Raipur
 *
 * TWO MECHANISMS, AND ONLY ONE OF THEM IS A SECOND FACTOR
 * ------------------------------------------------------
 * The inline code is generated by the server and returned to whoever asked
 * for it. Typing it back proves attention, not identity — anyone who can
 * reach the endpoint can request one and read it. It is a deliberate second
 * step on a consequential action, which is worth having, and it is not
 * authentication.
 *
 * TOTP is. The secret is enrolled once into an authenticator app and sealed
 * in the database; a correct code proves the person holding the account has
 * the enrolled device in their hand. It works with no network, which is what
 * makes it usable on a shop floor.
 *
 * SO THE RULE IS: TOTP IF ENROLLED, INLINE IF NOT
 * -----------------------------------------------
 * Enrolment is what makes the strong factor mandatory, per person, with no
 * code change and no flag — and it degrades in the right direction, because
 * nobody is locked out of releasing a wagon mid-pilot by a security
 * improvement they have not been onboarded to yet.
 *
 * The rule lived in the release-signoff route and nowhere else, so a stage
 * override and an audit export — both consequential, both able to move a
 * wagon or its record — accepted the weaker mechanism from someone who had
 * an authenticator enrolled. Written once here for the same reason the OTP
 * bypass strings were centralised: a rule copied to a second site is a rule
 * that will be forgotten at a third.
 */

import type { DatabaseSync } from 'node:sqlite';
import { TotpService } from './totpService.ts';
import type { OtpAction } from '../../../shared/types.ts';

export interface SecondFactorResult {
  ok: boolean;
  /** Which mechanism actually cleared it, for the audit record. */
  factorUsed?: 'TOTP' | 'INLINE_OTP';
  /**
   * True when the signer is not enrolled and this function checked nothing —
   * the caller's own verification is what stands. Present so a caller cannot
   * read `ok: true` as "a second factor was proven".
   */
  deferredToCaller?: boolean;
  statusCode?: number;
  error?: string;
  message?: string;
}

export function verifySecondFactor(
  db: DatabaseSync,
  params: {
    userId: string | undefined;
    action: OtpAction;
    /** Code from the authenticator app, when the signer has one enrolled. */
    totpCode?: string | null;
    /** The inline confirmation code, for signers who have not enrolled. */
    otpToken?: string | null;
    /** What is being authorised, for the refusal message. */
    describeAction: string;
  }
): SecondFactorResult {
  const { userId, action, totpCode, otpToken, describeAction } = params;

  if (!userId) {
    return {
      ok: false,
      statusCode: 401,
      error: 'UNAUTHORIZED',
      message: `${describeAction} must name the person doing it.`
    };
  }

  const totpService = new TotpService(db);

  if (totpService.isEnrolled(userId)) {
    /*
     * Enrolled means enrolled. The inline code is refused outright rather
     * than accepted as a fallback — otherwise enrolling would add a step
     * without removing the weaker path, which is not an improvement.
     */
    if (!totpCode) {
      return {
        ok: false,
        statusCode: 401,
        error: 'TOTP_REQUIRED',
        message:
          `You have an authenticator enrolled, so ${describeAction} requires the six-digit ` +
          `code from it. The on-screen confirmation code is not accepted once an ` +
          `authenticator is set up.`
      };
    }

    const result = totpService.verify(userId, String(totpCode));
    if (!result.ok) {
      return {
        ok: false,
        statusCode: 401,
        error: 'INVALID_TOTP',
        message: result.reason || 'That authenticator code was not accepted.'
      };
    }
    return { ok: true, factorUsed: 'TOTP' };
  }

  /*
   * Not enrolled: this function has no opinion, and the caller's existing
   * check stands.
   *
   * It used to verify the inline code here instead, and that made the
   * override WEAKER rather than stronger — the lifecycle engine refuses a
   * fabricated 'test_' token on an override, while otpService honours
   * 'test_token_*' outside production so the suites can run. Routing the
   * override through this path therefore let a made-up token authorise one,
   * which the adversarial suite caught immediately (PEN-02E).
   *
   * So this raises the bar for enrolled users and never lowers it for
   * anybody. Whatever the route already required, it still requires.
   */
  return { ok: true, factorUsed: 'INLINE_OTP', deferredToCaller: true };
}
