/**
 * RDSO G-95 Revision-II Deep Adversarial Stress & Empirical Verification Test Suite (Server Implementation)
 * Indian Railways Wagon Repair Shop (WRS) Raipur
 *
 * Generated by Challenger 1 (Milestone 1)
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import {
  classifySpring,
  getRDSOTable,
  validateClassificationRequest,
  RDSO_TABLES
} from '../../shared/classification/index.ts';
import type {
  BogieType,
  SpringCondition,
  SpringPosition,
  DamageType,
  ClassificationRequest
} from '../../shared/types.ts';

describe('Server Classification Engine — Deep Adversarial Stress Suite', () => {

  // -------------------------------------------------------------------------
  // 1. Floating-point Boundary & Micro-Epsilon Precision Tests
  // -------------------------------------------------------------------------
  describe('Dimension 1: Floating-Point Boundary & Micro-Epsilon Precision', () => {
    it('TC-ADV-SRV-01: Micro-epsilon boundary precision across all 18 RDSO tables', () => {
      let boundaryChecksCount = 0;

      for (const [tableKey, table] of Object.entries(RDSO_TABLES)) {
        // Ceiling test: Max height must PASS (Band I), Max + epsilon must CONDEMN
        const ceilPass = classifySpring({
          bogieType: table.bogieType,
          condition: table.condition,
          position: table.position,
          measuredHeight: table.condemningMaxHeight
        });
        assert.strictEqual(ceilPass.status, 'PASS', `${tableKey} ceiling exact must PASS`);
        assert.strictEqual(ceilPass.band, table.bands[0].band);

        for (const eps of [1e-9, 1e-6, 0.0001, 0.001, 0.01]) {
          const ceilCondemn = classifySpring({
            bogieType: table.bogieType,
            condition: table.condition,
            position: table.position,
            measuredHeight: table.condemningMaxHeight + eps
          });
          assert.strictEqual(ceilCondemn.status, 'CONDEMNED', `${tableKey} ceiling + ${eps} must CONDEMN`);
          assert.strictEqual(ceilCondemn.band, null);
          boundaryChecksCount++;
        }

        // Floor test: Min height must PASS (Lowest Band), Min - epsilon must CONDEMN
        const floorPass = classifySpring({
          bogieType: table.bogieType,
          condition: table.condition,
          position: table.position,
          measuredHeight: table.condemningMinHeight
        });
        assert.strictEqual(floorPass.status, 'PASS', `${tableKey} floor exact must PASS`);
        assert.strictEqual(floorPass.band, table.bands[table.bands.length - 1].band);

        for (const eps of [1e-9, 1e-6, 0.0001, 0.01]) {
          const floorCondemn = classifySpring({
            bogieType: table.bogieType,
            condition: table.condition,
            position: table.position,
            measuredHeight: table.condemningMinHeight - eps
          });
          assert.strictEqual(floorCondemn.status, 'CONDEMNED', `${tableKey} floor - ${eps} must CONDEMN`);
          assert.strictEqual(floorCondemn.band, null);
          boundaryChecksCount++;
        }

        // Internal band boundary transitions: exactly at B -> higher band; B - eps -> lower band
        for (let i = 0; i < table.bands.length - 1; i++) {
          const higher = table.bands[i];
          const lower = table.bands[i + 1];
          const b = higher.minHeight;

          // Exact boundary
          const resExact = classifySpring({
            bogieType: table.bogieType,
            condition: table.condition,
            position: table.position,
            measuredHeight: b
          });
          assert.strictEqual(resExact.status, 'PASS');
          assert.strictEqual(resExact.band, higher.band, `${tableKey} exact ${b} must be higher band ${higher.band}`);

          // Epsilon above boundary
          for (const eps of [1e-9, 1e-6, 0.001, 0.01]) {
            const resAbove = classifySpring({
              bogieType: table.bogieType,
              condition: table.condition,
              position: table.position,
              measuredHeight: b + eps
            });
            assert.strictEqual(resAbove.status, 'PASS');
            assert.strictEqual(resAbove.band, higher.band, `${tableKey} ${b}+${eps} must be ${higher.band}`);
            boundaryChecksCount++;
          }

          // Epsilon below boundary
          for (const eps of [1e-9, 1e-6, 0.001, 0.01]) {
            const resBelow = classifySpring({
              bogieType: table.bogieType,
              condition: table.condition,
              position: table.position,
              measuredHeight: b - eps
            });
            assert.strictEqual(resBelow.status, 'PASS');
            assert.strictEqual(resBelow.band, lower.band, `${tableKey} ${b}-${eps} must be ${lower.band}`);
            boundaryChecksCount++;
          }
        }
      }

      assert.ok(boundaryChecksCount > 500, `Executed ${boundaryChecksCount} boundary micro-step checks`);
    });
  });

  // -------------------------------------------------------------------------
  // 2. Micro-step Sweep Across All Tables
  // -------------------------------------------------------------------------
  describe('Dimension 2: Full Continuous Micro-Step Sweep (50,000+ Points)', () => {
    it('TC-ADV-SRV-02: Micro-step 0.02mm continuous sweep over all 18 tables', () => {
      let totalSteps = 0;

      for (const [tableKey, table] of Object.entries(RDSO_TABLES)) {
        const sweepMin = table.condemningMinHeight - 2.0;
        const sweepMax = table.condemningMaxHeight + 2.0;
        const step = 0.01;

        for (let h = sweepMin; h <= sweepMax + 0.0001; h += step) {
          const roundedH = Math.round(h * 1000) / 1000;
          totalSteps++;

          const res = classifySpring({
            bogieType: table.bogieType,
            condition: table.condition,
            position: table.position,
            measuredHeight: roundedH
          });

          if (roundedH < table.condemningMinHeight || roundedH > table.condemningMaxHeight) {
            assert.strictEqual(res.status, 'CONDEMNED', `Height ${roundedH} on ${tableKey} should be CONDEMNED`);
            assert.strictEqual(res.band, null);
            assert.strictEqual(res.bandRoman, null);
            assert.ok(res.condemnationReason);
          } else {
            assert.strictEqual(res.status, 'PASS', `Height ${roundedH} on ${tableKey} should PASS`);
            assert.ok(res.band !== null, `Band must not be null for ${roundedH} on ${tableKey}`);
            assert.ok(res.bandRoman !== null);
            assert.strictEqual(res.condemnationReason, null);
          }
        }
      }

      assert.ok(totalSteps > 25000, `Total micro-step evaluations: ${totalSteps}`);
    });
  });

  // -------------------------------------------------------------------------
  // 3. Out of Range & Extreme Inputs
  // -------------------------------------------------------------------------
  describe('Dimension 3: Out-of-Range, Extreme & Malformed Input Handling', () => {
    it('TC-ADV-SRV-03: Out-of-table values within gauge (100-450mm) return CONDEMNED', () => {
      const outOfRangeGaugeValues = [105.0, 150.0, 200.0, 240.0, 320.0, 400.0, 449.0];

      for (const val of outOfRangeGaugeValues) {
        const res = classifySpring({
          bogieType: 'CASNUB_22_NLB',
          condition: 'USED',
          position: 'OUTER',
          measuredHeight: val
        });

        assert.strictEqual(res.status, 'CONDEMNED', `Val ${val} must be CONDEMNED`);
        assert.strictEqual(res.band, null);
        assert.strictEqual(res.bandRoman, null);
        assert.ok(res.condemnationReason);
      }
    });

    it('TC-ADV-SRV-03B: Non-numeric, NaN, Infinity, negative and outside gauge limits throw validation error', () => {
      const invalidValues = [-100, -1, 0, 10.0, 99.9, 450.1, 999999.0, NaN, Infinity, -Infinity];

      for (const val of invalidValues) {
        assert.throws(
          () => {
            classifySpring({
              bogieType: 'CASNUB_22_NLB',
              condition: 'USED',
              position: 'OUTER',
              measuredHeight: val
            });
          },
          /Invalid classification request|outside physically permissible/
        );
      }
    });
  });

  // -------------------------------------------------------------------------
  // 4. Defect Combinations
  // -------------------------------------------------------------------------
  describe('Dimension 4: Defect Flag Combinations & Notes', () => {
    it('TC-ADV-SRV-04: Any physical defect forces CONDEMNED on every band and table', () => {
      const defects: DamageType[] = ['CRACK', 'CORROSION', 'DEFORMATION', 'OTHER'];
      const notesList = [
        '',
        'Surface pitting depth 2mm',
        'Coil fracture at bottom turn',
        'Special chars <>!@#$%',
        'Hindi text: दरार'
      ];

      for (const [tableKey, table] of Object.entries(RDSO_TABLES)) {
        for (const d of defects) {
          for (const notes of notesList) {
            const midH = (table.condemningMinHeight + table.condemningMaxHeight) / 2;
            const res = classifySpring({
              bogieType: table.bogieType,
              condition: table.condition,
              position: table.position,
              measuredHeight: midH,
              damageType: d,
              damageNotes: notes
            });

            assert.strictEqual(res.status, 'CONDEMNED', `Defect ${d} on ${tableKey} must condemn`);
            assert.strictEqual(res.band, null);
            assert.strictEqual(res.bandRoman, null);
            assert.ok(res.condemnationReason?.includes(d));
            if (notes.length > 0) {
              assert.ok(res.condemnationReason?.includes(notes));
            }
          }
        }
      }
    });
  });

  // -------------------------------------------------------------------------
  // 5. Complete Matrix of Bogies, Conditions, and Spring Positions
  // -------------------------------------------------------------------------
  describe('Dimension 5: Complete Matrix Coverage (3 Bogies x 2 Conditions x 5 Positions)', () => {
    it('TC-ADV-SRV-05: Validates all 30 matrix combinations', () => {
      const bogies: BogieType[] = ['CASNUB_22_NLB', 'CASNUB_22_HS', 'CASNUB_22_RFT'];
      const conditions: SpringCondition[] = ['USED', 'NEW'];
      const positions: SpringPosition[] = ['OUTER', 'INNER', 'SNUBBER', 'SNUBBER_OUTER', 'SNUBBER_INNER'];

      for (const bogie of bogies) {
        for (const cond of conditions) {
          for (const pos of positions) {
            const table = getRDSOTable(bogie, cond, pos);
            assert.ok(table !== null, `Table must exist for ${bogie} ${cond} ${pos}`);
            assert.strictEqual(table.bands.length, cond === 'USED' ? 6 : 3);

            // Test midpoint height
            const midH = (table.condemningMinHeight + table.condemningMaxHeight) / 2;
            const res = classifySpring({
              bogieType: bogie,
              condition: cond,
              position: pos,
              measuredHeight: midH
            });

            assert.strictEqual(res.status, 'PASS');
            assert.ok(res.band !== null);
            assert.ok(res.bandRoman !== null);
            assert.strictEqual(res.tableReference, table.tableNumber);
          }
        }
      }
    });
  });

  // -------------------------------------------------------------------------
  // 6. Randomized Property-Based Invariant Fuzzing (10,000 runs)
  // -------------------------------------------------------------------------
  describe('Dimension 6: Property-Based Randomized Fuzzing (10,000 Cases)', () => {
    it('TC-ADV-SRV-06: 10,000 randomized classifications verify all mathematical invariants', () => {
      const bogies: BogieType[] = ['CASNUB_22_NLB', 'CASNUB_22_HS', 'CASNUB_22_RFT'];
      const conditions: SpringCondition[] = ['USED', 'NEW'];
      const positions: SpringPosition[] = ['OUTER', 'INNER', 'SNUBBER', 'SNUBBER_OUTER', 'SNUBBER_INNER'];
      const damages: DamageType[] = ['NONE', 'CRACK', 'CORROSION', 'DEFORMATION', 'OTHER'];

      let seed = 123456789;
      function rnd(): number {
        seed = (seed * 1103515245 + 12345) & 0x7fffffff;
        return seed / 0x7fffffff;
      }

      let passed = 0;
      let condemned = 0;

      for (let i = 0; i < 10000; i++) {
        const bogie = bogies[Math.floor(rnd() * bogies.length)];
        const cond = conditions[Math.floor(rnd() * conditions.length)];
        const pos = positions[Math.floor(rnd() * positions.length)];
        const damage = damages[Math.floor(rnd() * damages.length)];
        const height = Math.round((200.0 + rnd() * 120.0) * 100) / 100;

        const req: ClassificationRequest = {
          bogieType: bogie,
          condition: cond,
          position: pos,
          measuredHeight: height,
          damageType: damage
        };

        const res1 = classifySpring(req);
        const res2 = classifySpring(req);

        // Invariant 1: Determinism
        assert.strictEqual(res1.status, res2.status);
        assert.strictEqual(res1.band, res2.band);
        assert.strictEqual(res1.bandRoman, res2.bandRoman);

        // Invariant 2: No undefined values
        assert.ok(res1.status !== undefined);
        assert.ok(res1.validRange !== undefined);
        assert.ok(res1.tableReference !== undefined);

        // Invariant 3: Correct Status Contract
        if (res1.status === 'PASS') {
          passed++;
          assert.strictEqual(damage, 'NONE');
          assert.ok(res1.band !== null);
          assert.ok(res1.bandRoman !== null);
          assert.ok(height >= res1.validRange.min && height <= res1.validRange.max);
          assert.strictEqual(res1.condemnationReason, null);
        } else {
          condemned++;
          assert.strictEqual(res1.status, 'CONDEMNED');
          assert.strictEqual(res1.band, null);
          assert.strictEqual(res1.bandRoman, null);
          assert.ok(typeof res1.condemnationReason === 'string' && res1.condemnationReason.length > 0);
        }
      }

      assert.ok(passed > 0, `Passed: ${passed}`);
      assert.ok(condemned > 0, `Condemned: ${condemned}`);
      assert.strictEqual(passed + condemned, 10000);
    });
  });

});
